# Generated by Django 2.2.1 on 2019-06-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceName', models.CharField(default='小说源名字', max_length=30, verbose_name='源名称')),
                ('searchRequests', models.CharField(default='url="",method="", data="", charset=""', max_length=200, verbose_name='源搜索规则')),
                ('searchFilter', models.CharField(default='bookName="",bookAuthor="",bookNewestChapterName="",bookUpdateTime="",bookUrl=""', max_length=200, verbose_name='源搜索结果过滤')),
            ],
        ),
    ]
