# Generated by Django 2.2.1 on 2019-06-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booksearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksearch',
            old_name='sourceName',
            new_name='source_name',
        ),
        migrations.RemoveField(
            model_name='booksearch',
            name='searchFilter',
        ),
        migrations.RemoveField(
            model_name='booksearch',
            name='searchRequests',
        ),
        migrations.AddField(
            model_name='booksearch',
            name='requests_charset',
            field=models.CharField(default='', max_length=200, verbose_name='网站编码'),
        ),
        migrations.AddField(
            model_name='booksearch',
            name='requests_data',
            field=models.CharField(default='', max_length=200, verbose_name='post访问数据'),
        ),
        migrations.AddField(
            model_name='booksearch',
            name='requests_method',
            field=models.CharField(default='', max_length=200, verbose_name='访问方式post或get'),
        ),
        migrations.AddField(
            model_name='booksearch',
            name='requests_url',
            field=models.CharField(default='', max_length=200, verbose_name='网址'),
        ),
        migrations.AddField(
            model_name='booksearch',
            name='search_key',
            field=models.CharField(default='', max_length=200, verbose_name='源搜索键'),
        ),
        migrations.AddField(
            model_name='booksearch',
            name='search_value',
            field=models.CharField(default='', max_length=200, verbose_name='源搜索键'),
        ),
    ]
