# Generated by Django 2.2.1 on 2019-06-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190626_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksearch',
            name='requests_charset',
            field=models.CharField(default='utf-8', max_length=10, verbose_name='网站编码'),
        ),
        migrations.AlterField(
            model_name='booksearch',
            name='requests_data',
            field=models.CharField(default='', max_length=100, verbose_name='post访问数据'),
        ),
        migrations.AlterField(
            model_name='booksearch',
            name='search_value',
            field=models.CharField(default='', max_length=100, verbose_name='源搜索值'),
        ),
    ]
