# Generated by Django 2.2.1 on 2019-06-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190626_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksearch',
            name='search_key',
            field=models.CharField(default='', max_length=200, verbose_name='源搜索键'),
        ),
        migrations.AlterField(
            model_name='booksearch',
            name='search_value',
            field=models.CharField(default='', max_length=200, verbose_name='源搜索值'),
        ),
    ]
