# Generated by Django 2.2.1 on 2019-07-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190626_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookIntroduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=30, verbose_name='源名称')),
                ('requests_method', models.CharField(default='post', max_length=10, verbose_name='访问方式post或get')),
                ('requests_data', models.CharField(default='', max_length=100, verbose_name='访问数据')),
                ('requests_charset', models.CharField(default='utf-8', max_length=10, verbose_name='网站编码')),
                ('introduce_key', models.TextField(verbose_name='源小说介绍键')),
                ('introduce_value', models.TextField(verbose_name='源小说介绍值')),
            ],
        ),
        migrations.AlterField(
            model_name='booksearch',
            name='requests_data',
            field=models.CharField(max_length=100, verbose_name='访问数据'),
        ),
    ]
