# Generated by Django 2.2.1 on 2019-07-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190701_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookintroduce',
            name='requests_url',
        ),
    ]
