# Generated by Django 2.2.1 on 2019-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='list_key',
        ),
        migrations.RemoveField(
            model_name='booklist',
            name='list_value',
        ),
        migrations.AddField(
            model_name='booklist',
            name='list_kv',
            field=models.TextField(default=111, verbose_name='源小说列表url和章节名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookintroduce',
            name='requests_method',
            field=models.CharField(default='get', max_length=10, verbose_name='访问方式post或get'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='requests_method',
            field=models.CharField(default='get', max_length=10, verbose_name='访问方式post或get'),
        ),
        migrations.AlterField(
            model_name='booksearch',
            name='requests_method',
            field=models.CharField(default='get', max_length=10, verbose_name='访问方式post或get'),
        ),
    ]
