# Generated by Django 2.2.1 on 2019-07-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190702_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=30, verbose_name='源名称')),
                ('requests_url', models.CharField(max_length=100, verbose_name='域名')),
                ('requests_method', models.CharField(default='get', max_length=10, verbose_name='访问方式post或get')),
                ('requests_data', models.CharField(default='{}', max_length=100, verbose_name='访问数据')),
                ('requests_charset', models.CharField(default='utf-8', max_length=10, verbose_name='网站编码')),
                ('content_kv', models.TextField(verbose_name='源小说章节内容')),
            ],
        ),
    ]
