# Generated by Django 2.2.1 on 2019-07-04 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bookcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcontent',
            name='requests_url',
        ),
    ]
