# Generated by Django 2.2.1 on 2019-07-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=14, verbose_name='用户名')),
                ('password', models.CharField(max_length=14, verbose_name='密码')),
                ('bookrack', models.TextField(blank=True, verbose_name='书架')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
