# Generated by Django 2.2.1 on 2019-07-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.CharField(max_length=10, verbose_name='创建时间'),
        ),
    ]
