# Generated by Django 2.2.1 on 2019-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190720_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=1, max_length=100, verbose_name='token验证'),
            preserve_default=False,
        ),
    ]
