# Generated by Django 2.2.1 on 2019-07-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190728_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookrack',
            field=models.TextField(null=True, verbose_name='书架'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=100, null=True, verbose_name='token验证'),
        ),
    ]
